<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;&lt;div&gt;[&nbsp;Shameless&nbsp;ping&nbsp;]&lt;br&gt;&lt;br&gt;Is&nbsp;there&nbsp;any&nbsp;progress&nbsp;with&nbsp;the&nbsp;release?&lt;br&gt;&lt;/div&gt;&lt;div&gt;Or&nbsp;any&nbsp;indication&nbsp;about&nbsp;when&nbsp;it&nbsp;could&nbsp;take&nbsp;place?&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&gt;&gt;&nbsp;2)&nbsp;Potential&nbsp;DoS&nbsp;when&nbsp;importing&nbsp;an&nbsp;RSA&nbsp;key&nbsp;(segfault&nbsp;of&nbsp;the&nbsp;interpreter)&lt;br&gt;<br>
&lt;div&nbsp;class=&quot;gmail_extra&quot;&gt;&lt;div&nbsp;class=&quot;gmail_quote&quot;&gt;&lt;blockquote&nbsp;class=&quot;gmail_quote&quot;&nbsp;style=&quot;margin:0&nbsp;0&nbsp;0&nbsp;.8ex;border-left:1px&nbsp;#ccc&nbsp;solid;padding-left:1ex&quot;&gt;&lt;div&nbsp;class=&quot;&quot;&gt;<br>
&gt;&nbsp;I&nbsp;assume&nbsp;you&nbsp;mean&nbsp;the&nbsp;floating-point&nbsp;exception&nbsp;that&nbsp;occurs&nbsp;when&nbsp;you&nbsp;pass&nbsp;an&lt;br&gt;<br>
&gt;&nbsp;even&nbsp;modulus&nbsp;to&nbsp;RSA.construct?&lt;br&gt;<br>
&lt;br&gt;<br>
&lt;/div&gt;Correct.&lt;br&gt;<br>
&lt;div&nbsp;class=&quot;&quot;&gt;&lt;br&gt;<br>
&gt;&nbsp;&lt;a&nbsp;href=&quot;https://bugs.launchpad.net/pycrypto/+bug/1193521&quot;&nbsp;target=&quot;_blank&quot;&gt;https://bugs.launchpad.net/pycrypto/+bug/1193521&lt;/a&gt;&lt;br&gt;<br>
&gt;&nbsp;&lt;a&nbsp;href=&quot;https://github.com/dlitz/pycrypto/pull/50&quot;&nbsp;target=&quot;_blank&quot;&gt;https://github.com/dlitz/pycrypto/pull/50&lt;/a&gt;&lt;br&gt;<br>
&gt;&lt;br&gt;<br>
&gt;&nbsp;On&nbsp;pull&nbsp;request&nbsp;#50&nbsp;(&quot;Add&nbsp;checks&nbsp;to&nbsp;verify&nbsp;correctness&nbsp;of&nbsp;RSA/DSA/ElGamal&lt;br&gt;<br>
&gt;&nbsp;keys&quot;),&nbsp;it&nbsp;would&nbsp;be&nbsp;helpful&nbsp;if&nbsp;others&nbsp;could&nbsp;chime&nbsp;in&nbsp;about&nbsp;the&nbsp;potential&nbsp;for&lt;br&gt;<br>
&gt;&nbsp;leaking&nbsp;private&nbsp;keys&nbsp;via&nbsp;timing&nbsp;side-channels.&lt;br&gt;<br>
&lt;br&gt;<br>
&lt;/div&gt;In&nbsp;addition&nbsp;to&nbsp;fixing&nbsp;the&nbsp;DoS,&nbsp;PR&nbsp;#50&nbsp;also&nbsp;replaced&nbsp;the&nbsp;custom&lt;br&gt;<br>
KeyFormatError&nbsp;exception&nbsp;with&nbsp;ValueError&nbsp;in&nbsp;the&nbsp;DSA&nbsp;code&nbsp;(I&nbsp;wrote&nbsp;it&lt;br&gt;<br>
before&nbsp;you&nbsp;expressed&nbsp;preference&nbsp;for&nbsp;not&nbsp;having&nbsp;custom&nbsp;exceptions&nbsp;at&lt;br&gt;<br>
all).&lt;br&gt;<br>
&lt;br&gt;<br>
I&nbsp;would&nbsp;actually&nbsp;apply&nbsp;first&nbsp;this&nbsp;other&nbsp;PR:&lt;br&gt;<br>
&lt;br&gt;<br>
&lt;a&nbsp;href=&quot;https://github.com/dlitz/pycrypto/pull/71&quot;&nbsp;target=&quot;_blank&quot;&gt;https://github.com/dlitz/pycrypto/pull/71&lt;/a&gt;&lt;br&gt;<br>
&lt;br&gt;<br>
Since&nbsp;there&nbsp;are&nbsp;2&nbsp;other&nbsp;exception&nbsp;types&nbsp;to&nbsp;fix.&lt;br&gt;<br>
Hopefully&nbsp;PR&nbsp;#50&nbsp;still&nbsp;applies&nbsp;cleanly&nbsp;after&nbsp;it.&lt;br&gt;<br>
&lt;/blockquote&gt;&lt;/div&gt;&lt;br&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;<br>

</tt>
